app:
    exception:
        user_already_exists: 'UÅ¼ytkownik z adresem email %username% istnieje w systemie.'
